config/routes.rb
Rails.application.routes.draw do
 
  root 'employees#index'
  resources :categories
  resources :suppliers
  resources :products do
     collection do
    get :image_data
   end
 end
  resources :customers
  resources :employees do
    collection do
     get :export_data
     post :data_check
     post :delete_number
    end
  end
  resources :departments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :phone_numbers, :dependent => :destroy
	belongs_to :department
	accepts_nested_attributes_for :phone_numbers
	validates :base_salary, numericality: true
	validates :dob , :da, :ta, :sex, :department_id,:salute, presence: true
    validates :name, :address, presence: true ,format: {with: /[a-zA-Z]/},on: :create
    validates :name, :address, presence: true ,format: {with: /[a-zA-Z]/},on: :update
    validates_associated :phone_numbers
   
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :total_salary
  def index
    @employees = Employee.order("updated_at desc").paginate(page: params[:page],per_page: 10)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EmployeePdf.new( @employees )
        send_data pdf.render, filename: "employees.pdf",type: "application/pdf", disposition: "attachment"
      end
    end
  end

  def new
    @dep_options = Department.all.map { |d| [ d.name,d.id ] } 
    @employee = Employee.new
  end

  def create
     # debugger
     @dep_options = Department.all.map { |d| [ d.name,d.id ] } 
     @employee = Employee.new(employee_params)
     if @employee.save
      p_num = params[:employee][:phone_number]
      if p_num.present?
        p_num.each do|p_no| 
          @employee.phone_numbers.create!(phone_num: p_no)
        end
      end
      flash[:success] = "Employee created successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "Error occure"
      render 'new'
    end
  end

  def edit
    # debugger
    @dep_options = Department.all.map { |d| [ d.name,d.id ] }
    @employee = Employee.find_by_id(params[:id])
  end

  def update
    #debugger
    @dep_options = Department.all.map { |d| [ d.name,d.id ] }
    @employee = Employee.find_by_id(params[:id])
    if @employee.update(employee_params)
      p_num = params[:employee][:phone_number]
      if p_num.present?
        p_num.each do|p_no| 
          @employee.phone_numbers.create!(phone_num: p_no)
        end
      end
      flash[:success] = "Employee updated successfully"
      redirect_to root_path
    else
      flash.now[:error] = "Error In Updating"
      render 'edit'
    end
  end

  def show 
  end

  def destroy
    emp = Employee.find_by_id(params[:id])
    emp.destroy
    redirect_to employees_path
  end

  def export_data
    headers['Content-Type'] = "application/vnd.ms-excel"
    headers['Content-Disposition']  = 'attachment; filename="record.xls"'
    headers['Cache-Control'] = ''
    @employees  = Employee.all
  end

  def data_check 
    #debugger 
    if(params[:Exprt].present?)
      data_value = params[:Exprt]
      if(data_value == 'Excel')
        redirect_to export_data_employees_path(format: "xls")
      else
        redirect_to employees_path(format: 'pdf')
      end
    end
  end

  def delete_number
    #debugger
    p_num = params[:deletedPhones] 
    e1 = Employee.find(params[:id])
    if p_num.present? && e1.present?
      p_num.each do|p_number|
        e1.phone_numbers.find_by_phone_num(p_number).destroy  
      end
    end
    render json: {status: 'ok', message: "proceed" }
  end

  private

  def total_salary(sal,da,ta)
    if sal.present? && da.present? && ta.present?
      d_allowance = (sal*da)/100
      t_allowance = (sal*ta)/100
      return sal+d_allowance+t_allowance
    end
  end


  def employee_params
    params.require(:employee).permit(:name,:base_salary,:address,:department_id,:dob,:da,:ta,:salute,:sex,phone_numbers_attributes: [:id,:phone_num])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	
end

app/views/employees/_empmodel.html.erb
<!-- Modal -->
      <div class="modal fade" id="exampleModal<%= emp.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">

            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              Are you sure?
            </div>

            <!-- Delete button in the footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
              <%= link_to "Delete", employee_path(emp), method: :delete, class: 'btn btn-outline-danger' %>
            </div>

        </div>

app/views/employees/_reportcard.html.erb
<tr>
	<td><%= emp.salute %></td>
	<td><%= emp.name %></td>
	<td><%= emp.dob.strftime("%b/%d/%Y") %></td>
	<td><%= emp.address %></td>
	<td><%= total_salary(emp.base_salary,emp.da,emp.ta)%></td>
</tr>

app/views/employees/_sidebar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to 'Employees',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-th" aria-hidden="true"></i></span>
          <%= link_to "Departments",departments_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to "Suppliers",suppliers_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tag" aria-hidden="true"></i></span>
          <%= link_to "Categories",categories_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span>
          <%= link_to "Products",products_path ,class: "nav-link"%>
        </li> 
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-address-card" aria-hidden="true"></i></span>
          <%= link_to "Customers",customers_path ,class: "nav-link"%>
        </li>   
  </ul>
</div>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="container">
      <%= flash_messages %>
    </div><!-- /container -->
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Edit Employee</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@employee) do |f| %>
            <% if @employee.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @employee.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.select :salute, (["Mr","Miss"])%>
            <%= f.text_field :name,class: 'form-control'%>
            <%= f.select(:department_id, @dep_options,{:include_blank => true})%>
            <%= f.label "Gender" %><br>
            <%= f.radio_button :sex,'male'  %>   
            <%= f.radio_button :sex,'female' %><br>
            <%= f.date_field :dob  %>
            <div class="field_wrapper">
              <div> 
                Add Phone <br> <a href="javascript:void(0);" class="add_button" title="Add field"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a>
                <br>
                <% i = 0 %>   
                <%= f.nested_fields_for :phone_numbers do |numbers_form  | %>
                <% i+=1%>     
                <%= numbers_form.text_field :phone_num, class: "phone-number" + i.to_s %>
                <a href="javascript:void(0);" class="remove_button"> <i type='button' class="fa fa-minus-circle fa-2x" aria-hidden="true" id="btn-delete-phone" data-id='<%= i %>'></i></a>
                <!--  <button type='button' id="btn-delete-phone" data-id='<%= i %>' class="btn btn-info">X</button>  -->
                <% end %> 


              </div>
            </div><br>
            <%= f.text_field :base_salary %><br>
            <%= f.select :da, ((0..20).map {|i| [i,i] }) %><br>
            <%= f.select :ta, ((0..15).map {|i| [i,i] }) %><br>
            <%= f.text_area :address, class: 'form-control' %><br>
            <%= f.submit "Update Employee" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
 var deletedPhones = [];
 $(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var btnDelete = $('#btn-delete-phone');
    var fieldHTML = '<div><input type="text" name="employee[phone_number][]" value=""/><a href="javascript:void(0);" class="remove_button"> <i class="fa fa-minus-circle fa-2x" aria-hidden="true"></i></a></div>'; //New input field html 
    var x = 1; //Initial field counter is 1
    
    //Once add button is clicked
    $(addButton).click(function(){
        //Check maximum number of input fields
        if(x < maxField){ 
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); //Add field html
          }
        });
    
    //Once remove button is clicked
    $(wrapper).on('click', '.remove_button', function(e){
      e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
      });

    $(wrapper).on('click', '#btn-delete-phone',deletePhone);

  });

 var deletePhone = function(){
  var $btnDelete = $(this);
  var id = $btnDelete.data('id');
  var $phone = $('.phone-number'+id);
  var phone = $phone.val();
  deletedPhones.push(phone);
  var fieldset = $(this).closest('fieldset'); 
  if(fieldset)
  {
    fieldset.remove();
  }
  // $phone.hide();
  removeNumber(phone);

}

var removeNumber = function(number){
 $.ajax({
   type: "POST",
   beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))}, 
   url: "/employees/delete_number",
   data: {deletedPhones: [number], id: '<%= @employee.id %>'},
   dataType: "json",
   success: function(data, textStatus, jqXHR){
    // location.reload();
  },
  error: function(jqXHR, textStatus, errorThrown){
    console.log(errorThrown);
  }
});
}

$(function() {
    // put your code here
    $('#pre_loader').hide();
});

</script>

app/views/employees/export_data.html.erb
<table border="1" id="doc">
	<tr>
	<td>Salute</td>
	<td>Name</td>
	<td>Dob</td>
	<td>Address</td>
	<td>Salary</td>
    </tr>
	<% @employees.each do |emp| %>
	<%= render "reportcard", emp: emp %>
	<% end %>
</table>

app/views/employees/index.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->

</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>

</div>



<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
  <div class="container-fluid">
<div class="row">
 <div class="col-md-12">
  <div class="page-header"  style="margin-top: 5%">
   <%= link_to 'Add Employee', new_employee_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
 </div>
</div>
</div>
<div class="container">

  <%= flash_messages %>
</div><!-- /container -->
<section class="wrap page-addVendors">
 <div class="row">
   <div class="col-md-9 offset-md-2">
    <div class="col-md-8">
      <%= form_tag("/employees/data_check", remote: true ,id: "exp_data") do %>
      <div class="row">
        <div class="col-md-4">
          <%= select_tag "Exprt",options_for_select(["Excel","Pdf"]),class: "v-control input-xs" %>
        </div>
        <div class="col-md-2">
          <%= submit_tag("Print",class: "v-btn v-btn-primary btn-sm no-round  btn-shadow") %>
        </div>
      </div>
      <% end %>
    </div>
    <br>
    <div class="block bx-shadow skin-light">
     <div class="content">
      <table id="example" class="table table-striped">
       <thead>
        <tr>
          <!-- <th>Emp Detail</th> -->
          <th>Salute</th>
          <th>Name</th>
          <th>Gender </th>
          <th>DOB</th>
          <th>Address</th>
          <th>Salary</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
       <% @employees.each do |emp| %>
       <tr>
         <% if emp.present? %>
         <td><%= emp.salute %></td>
         <td><%= emp.name %> </td>
         <td><%= emp.sex %></td>
         <td><%= emp.dob.strftime("%b/%d/%Y") %></td>
         <td><%= emp.address %></td>
         <td><%= total_salary(emp.base_salary,emp.da,emp.ta) %></td>
         <% end %>
         <td>
           <%= link_to edit_employee_path(emp) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
           <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
           <% end %>
               <!-- Delete Button showing the modal Start-->
               <a data-toggle="modal" data-target="#exampleModal<%= emp.id %>" class="v-btn v-btn-transparent ft-primary icon icon-xs uppercase">
               <i
                 class="fa fa-trash "></i>
               </a>
           <%= render 'empmodel' ,:emp => emp %>
           <!-- Delete Button shoing the model End--->
         </td>
       </td>
     </tr>
     <% end %>
   </tbody>
 </table>
</div>
</div>
</div>
</div>
</div>
</div>
<%= will_paginate @employees, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: "right floated", inner_window: 3 %>
</div>
</section>
 </div>
</div>
<script type="text/javascript">
   var close;
   close = setTimeout(function(){
        $('.alert').fadeOut('slow');
        myStop();
  }, 5000);
   function myStop(){
     clearTimeout(close);
   }
   
   $('#pre_loader').hide();
</script>

app/views/employees/new.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Add Employee</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@employee) do |f| %>
            <% if @employee.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @employee.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.select :salute, (["Mr","Miss"])%>
            <%= f.text_field :name,class: 'form-control'%>
            <%= f.select(:department_id, @dep_options,{:include_blank => true})%>
            <%= f.label "Gender" %><br>
            <%= f.radio_button :sex,'male'  %>   
            <%= f.radio_button :sex,'female' %><br>
            <%= f.date_field :dob  %>
            <div class="field_wrapper">
              <div> 
                Add Phone <br> <a href="javascript:void(0);" class="add_button" title="Add field"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a>
                <br>
                <% i = 0 %>   
                <%= f.nested_fields_for :phone_numbers do |numbers_form  | %>
                <% i+=1%>     
                <%= numbers_form.text_field :phone_num, class: "phone-number" + i.to_s %>
                <a href="javascript:void(0);" class="remove_button"> <i type='button' class="fa fa-minus-circle fa-2x" aria-hidden="true" id="btn-delete-phone" data-id='<%= i %>'></i></a>
                <!--  <button type='button' id="btn-delete-phone" data-id='<%= i %>' class="btn btn-info">X</button>  -->
                <% end %> 


              </div>
            </div><br>
            <%= f.text_field :base_salary %><br>
            <%= f.select :da, ((0..20).map {|i| [i,i] }) %><br>
            <%= f.select :ta, ((0..15).map {|i| [i,i] }) %><br>
            <%= f.text_area :address, class: 'form-control' %><br>
            <%= f.submit "Create Employee" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
</div>

</style>
<script type="text/javascript">
  $(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var fieldHTML = '<div><input type="text" name="employee[phone_number][]" value=""/><a href="javascript:void(0);" class="remove_button"> <i class="fa fa-minus-circle fa-2x" aria-hidden="true"></i></a></div>'; //New input field html 
    var x = 1; //Initial field counter is 1
    
    //Once add button is clicked
    $(addButton).click(function(){
        //Check maximum number of input fields
        if(x < maxField){ 
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); //Add field html
          }
        });
    
    //Once remove button is clicked
    $(wrapper).on('click', '.remove_button', function(e){
      e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
      });
  });
  $(function() {
    // put your code here
    $('#pre_loader').hide();
});

</script>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>