config/routes.rb
Rails.application.routes.draw do
 
  root 'employees#index'
  resources :categories
  resources :suppliers
  resources :products do
     collection do
    get :image_data
   end
 end
  resources :customers
  resources :employees do
    collection do
     get :export_data
     post :data_check
     post :delete_number
    end
  end
  resources :departments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  validates :name, presence: :true ,format: {with: /[a-zA-Z]/},on: :create
  validates :name, presence: :true ,format: {with: /[a-zA-Z]/},on: :update
  validates_uniqueness_of :name ,on: :create
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
   @departments = Department.all.order("updated_at desc")
 end

 def new
   @department = Department.new
 end

 def create
    #debugger
    @department = Department.new(department_params)
    respond_to do |format|
    if @department.save
      format.html { redirect_to departments_path ,success: 'Department was successfully created.'}
   else
     format.html {render :new , notice: "Error in Creating department" }
   end
 end
  end

  def edit
   @department = Department.find(params[:id])
  end

 def update
    #debugger
    @department = Department.find(params[:id])
    if @department.update(department_params)
      flash[:success] = "Department updated successfully"
      redirect_to departments_path
    else
      render 'edit'
    end
  end

  def destroy
    #debugger
    @department = Department.find(params[:id])
     respond_to do |format|
    if @department.employees.present?
      format.html { redirect_to departments_path ,notice: 'Department have employees so cannot be deleted'}
    else
      @department.destroy
      format.html { redirect_to departments_path ,notice: 'Department Deleted successfully'}
    end
   end
  end

  private

  def department_params
   params.require(:department).permit(:name)
 end

end

app/views/departments/_deptmodel.html.erb
<!-- Modal -->
      <div class="modal fade" id="exampleModal<%= dep.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">

            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              Are you sure?
            </div>

            <!-- Delete button in the footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
              <%= link_to "Delete", department_path(dep), method: :delete, class: 'btn btn-outline-danger' %>
            </div>

        </div>

app/views/departments/_sidbar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to 'Employees',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-th" aria-hidden="true"></i></span>
          <%= link_to "Departments",departments_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to "Suppliers",suppliers_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tag" aria-hidden="true"></i></span>
          <%= link_to "Categories",categories_path ,class: "nav-link"%>
        </li>
         <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span>
          <%= link_to "Products",products_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-address-card" aria-hidden="true"></i></span>
          <%= link_to "Customers",customers_path ,class: "nav-link"%>
        </li>
  </ul>
</div>

app/views/departments/edit.html.erb
<div class="topBar skin-primary">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-4">
				<div class="logo">
					<span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
						<i class="fa fa-bars"></i>
					</span>

					<a href="/" class="logo-icon text-dark">
						<!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
						<span class="ft-dark-black">Employee Management</span>
					</a>
				</div>
			</div>
			<div class="col-md-4">
				<!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
			</div>
			<div class="col-md-4 text-right">
				<!-- Example split danger button -->
				<div class="btn-group mt-2">
					<%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
					<button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="sr-only">Toggle Dropdown</span>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="changePassword.php">Change Password</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="index.php">Logout</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'sidbar' %>
<div class="main-container">
<div class="container">
	<%= flash_messages %>
</div><!-- /container -->
<section class="wrap page-addVendors">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<div class="block bx-shadow">
				<div class="content v-form skin-light">
					<div class="row">
						<div class="col-md-12">
							<div class="page-header">
								<h4>Edit Department</h4>
							</div>  
						</div>
					</div>

					<div class="container col-md-8">
						<%= bootstrap_form_for(@department) do |f| %>

						<%= f.text_field :name %>

						<%= f.submit "Update Department", class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
</div>
<script type="text/javascript">
	$(function() {
    // put your code here
     $('#pre_loader').hide();
});

</script>

app/views/departments/index.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidbar' %>
<div class="main-container">
<div class="row">
 <div class="col-md-12">
  <div class="page-header"  style="margin-top: 5%">
   <%= link_to 'Add department', new_department_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
 </div>
</div>
</div>
<div class="container">
  <%= flash_messages %>
</div><!-- /container -->
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-9 offset-md-2">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
         <div class="content">
           <table id="example" class="table table-striped">
             <thead>
               <tr>
                 <th>Department Name</th>
               </tr>
             </thead>
             <tbody>
              <% @departments.each do |dep| %>
              <tr>
                <td><%= dep.name %></td>   <br>
                <td>
                 <%= link_to edit_department_path(dep) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
                 <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                 <% end %>
                 <!-- Delete Button showing the modal Start-->
                 <a data-toggle="modal" data-target="#exampleModal<%= dep.id %>" class="v-btn v-btn-transparent ft-primary icon icon-xs uppercase">
                   <i
                   class="fa fa-trash "></i>
                 </a>
                 <%= render 'deptmodel' ,:dep => dep %>
                 <!-- Delete Button showing the model End--->   
               </td>
             </tr>
             <% end %>

           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>
</section>
</div>
<script type="text/javascript">
   var close;
   close = setTimeout(function()
      {
        $('.alert').fadeOut('slow');
        myStop();
  }, 5000);
   function myStop(){
     clearTimeout(close);
   }

   $(function() {
    // put your code here
     $('#pre_loader').hide();
});
  </script>

app/views/departments/new.html.erb
<div class="topBar skin-primary">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-4">
				<div class="logo">
					<span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
						<i class="fa fa-bars"></i>
					</span>

					<a href="/" class="logo-icon text-dark">
						<!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
						<span class="ft-dark-black">Employee Management</span>
					</a>
				</div>
			</div>
			<div class="col-md-4">
				<!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
			</div>
			<div class="col-md-4 text-right">
				<!-- Example split danger button -->
				<div class="btn-group mt-2">
					<%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
					<button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="sr-only">Toggle Dropdown</span>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="changePassword.php">Change Password</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="index.php">Logout</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'sidbar' %>
<div class="main-container">
<section class="wrap page-addVendors">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<div class="block bx-shadow">
				<div class="content v-form skin-light">
					<div class="row">
						<div class="col-md-12">
							<div class="page-header">
								<h4>Create Employee</h4>
							</div>  
						</div>
					</div>

					<div class="container col-md-8">
						<%= bootstrap_form_for(@department) do |f| %>
						<%= f.text_field :name %>
						<%= f.submit "Create Derpartment",class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
</div>
<script type="text/javascript">
	$(function() {
    // put your code here
     $('#pre_loader').hide();
});

</script>