config/routes.rb
Rails.application.routes.draw do
 
  root 'employees#index'
  resources :categories
  resources :suppliers
  resources :products do
     collection do
    get :image_data
   end
 end
  resources :customers
  resources :employees do
    collection do
     get :export_data
     post :data_check
     post :delete_number
    end
  end
  resources :departments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
   validates :contact_name, :company_name,:contact_title,:city,:region,:country,:address, presence: true ,format: {with: /[a-zA-Z]/},on: :create
   validates :contact_name, :company_name,:contact_title,:city,:region,:country,:address, presence: true ,format: {with: /[a-zA-Z]/},on: :update

   validates :phone,:fax,:postal_code,presence: :true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  	@customers = Customer.all.order("updated_at desc").paginate(page: params[:page],per_page: 10)
  end

  def new
  	@customer = Customer.new
  end

  def create
   @customer = Customer.new(customer_params)
    respond_to do |format|
    if @customer.save
      format.html { redirect_to customers_path ,success: 'Department was successfully created.'}
   else
     format.html {render :new , notice: "Error in Creating department" }
   end
   end
  end

  def edit
  	@customer = Customer.find_by_id(params[:id])

  end

  def update
   @customer = Customer.find_by_id(params[:id])
   if @customer.update(customer_params)
      flash[:success] = "Customer updated successfully"
      redirect_to customers_path
    else
      render 'edit'
    end
  end

  def destroy
   @customer = Customer.find_by_id(params[:id])
   respond_to do |format|
    if @customer.destroy
      format.html { redirect_to customers_path ,notice: 'Customer Deleted successfully'}
    else 
      format.html { redirect_to customers_path ,notice: 'Customer cannot be deleted'}   
    end
   end
  end
   
 private

  def customer_params
   params.require(:customer).permit(:company_name,:contact_name,:contact_title,:address,:city,:region,:postal_code,:country,:phone,:fax)
  end
end

app/views/customers/_customermodel.html.erb
<!-- Modal -->
      <div class="modal fade" id="exampleModal<%= dep.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">

            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              Are you sure?
            </div>
            <!-- Delete button in the footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
              <%= link_to "Delete", customer_path(dep), method: :delete, class: 'btn btn-outline-danger' %>
            </div>

        </div>

app/views/customers/_sidebar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to 'Employees',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-th" aria-hidden="true"></i></span>
          <%= link_to "Departments",departments_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to "Suppliers",suppliers_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tag" aria-hidden="true"></i></span>
          <%= link_to "Categories",categories_path ,class: "nav-link"%>
        </li>
        
         <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span>
          <%= link_to "Products",products_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-address-card" aria-hidden="true"></i></span>
          <%= link_to "Customers",customers_path ,class: "nav-link"%>
        </li> 
        
  </ul>
</div>

app/views/customers/edit.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
  <div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Edit Customer</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@customer) do |f| %>
            <% if @customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @customer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.text_field :company_name,class: 'form-control'%>
             <%= f.text_field :contact_name,class: 'form-control'%>
              <%= f.text_field :contact_title,class: 'form-control'%>
              <%= f.text_area :address ,class: 'form-control'%>
              <%= f.text_field :city ,class: 'form-control'%>
              <%= f.text_field :region,class: 'form-control' %>
              <%= f.text_field :postal_code ,class: 'form-control'%>
              <%= f.text_field :country ,class: 'form-control'%>
              <%=  f.text_field :phone ,class: 'form-control'%>
              <%= f.text_field :fax ,class: 'form-control'%>
            <%= f.submit "Update Customer" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
</div>
<script type="text/javascript">
  $(function() {
    // put your code here
     $('#pre_loader').hide();
});

</script>

app/views/customers/index.html.erb
<div class="topBar skin-primary">
  <div class="container-fluid"> 
    <div class="row align-items-center">
      <div class="col-md-4">
        <div class="logo">
          <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
            <i class="fa fa-bars"></i>
          </span>
          <a href="/" class="logo-icon text-dark">
           <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
           <span class="ft-dark-black">Employee Management</span>
         </a>
       </div>
     </div>
     <div class="col-md-4">
      <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
    </div>
    <div class="col-md-4 text-right">
      <!-- Example split danger button -->
      <div class="btn-group mt-2">
        <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
        <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="changePassword.php">Change Password</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="index.php">Logout</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<%= render 'sidebar' %>
<div class="main-container">
  <div class="container-fluid">
    <!-- page-content -->
    <div class="row">
      <div class="col-md-12">
        <div class="page-header"  style="margin-top: 5%">
          <%= link_to 'Add Customer', new_customer_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
        </div>
      </div>
    </div>
    <div class="container">
      <%= flash_messages %>
    </div><!-- /container -->
    <section class="wrap page-addVendors">
      <div class="row">
        <div class="col-md-9 offset-md-2">
          <br>
          <div class="block bx-shadow skin-light">
            <div class="content">
              <table id="example" class="table table-striped">
                <thead>
                  <tr>
                    <th>Company Name</th>
                    <th>Contact Name</th>
                    <th>Contact Title</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Region</th>
                    <th>Postal Code</th>
                    <th>Country</th>
                    <th>Phone</th>
                    <th>Fax</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @customers.each do |cust| %>
                  <tr>
                    <% if cust.present? %>
                    <td><%= cust.company_name %> </td>
                    <td><%= cust.contact_name %> </td>
                    <td><%= cust.contact_title %> </td>
                    <td><%= cust.address %> </td>
                    <td><%= cust.city %> </td>
                    <td><%= cust.region %> </td>
                    <td><%= cust.postal_code %> </td>
                    <td><%= cust.country %> </td>
                    <td><%= cust.phone %> </td>
                    <td><%= cust.fax %> </td>
                    <% end %>
                    <td>
                      <%= link_to edit_customer_path(cust) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                      <% end %>
                      <!-- Delete Button showing the modal Start-->
                      <a data-toggle="modal" data-target="#exampleModal<%= cust.id %>" class="v-btn v-btn-transparent ft-primary icon icon-xs uppercase">
                        <i class="fa fa-trash "></i>
                      </a>
                      <%= render 'customermodel' ,:dep => cust %>
                      <!-- Delete Button showing the model End--->
                    </td>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= will_paginate @customers, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: "right floated", inner_window: 3 %>
</div>
</section>
</div>
</div>
<script type="text/javascript">
  var close;
  close = setTimeout(function()
  {
    $('.alert').fadeOut('slow');
    myStop();
  }, 5000);
  function myStop(){
    clearTimeout(close);
  }
  $(function() {
// put your code here
$('#pre_loader').hide();
});
</script>

app/views/customers/new.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
  <div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Add Customer</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@customer) do |f| %>
            <% if @customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @customer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.text_field :company_name,class: 'form-control'%>
             <%= f.text_field :contact_name,class: 'form-control'%>
              <%= f.text_field :contact_title,class: 'form-control'%>
              <%= f.text_area :address ,class: 'form-control'%>
              <%= f.text_field :city ,class: 'form-control'%>
              <%= f.text_field :region,class: 'form-control' %>
              <%= f.text_field :postal_code ,class: 'form-control'%>
              <%= f.text_field :country ,class: 'form-control'%>
              <%=  f.text_field :phone ,class: 'form-control'%>
              <%= f.text_field :fax ,class: 'form-control'%>
            <%= f.submit "Create Customer" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
</div>
<script type="text/javascript">
  $(function() {
    // put your code here
     $('#pre_loader').hide();
});

</script>