config/routes.rb
Rails.application.routes.draw do
 
  root 'employees#index'
  resources :categories
  resources :suppliers
  resources :products do
     collection do
    get :image_data
   end
 end
  resources :customers
  resources :employees do
    collection do
     get :export_data
     post :data_check
     post :delete_number
    end
  end
  resources :departments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :supplier
  belongs_to :category
  #validates :image ,presence: true
  validates :recorder_level,:quantity_per_unit, :unit_in_stock, :unit_price, numericality: true
  validates :product_name, :category_id,:supplier_id, presence: true ,on: :create
  validates :product_name, presence: true ,format: {with: /[a-zA-Z]/},on: :update
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order("updated_at desc").paginate(page: params[:page],per_page: 10)
  end

  def new
    @supply_options = Supplier.all.map { |d| [ d.company_name,d.id ] }
    @category_options = Category.all.map { |d| [ d.category_name,d.id ] }
    @product = Product.new
  end

  def create
    #debugger
    @supply_options = Supplier.all.map { |d| [ d.company_name,d.id ] }
    @category_options = Category.all.map { |d| [ d.category_name,d.id ] }
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created successfully."
      redirect_to products_path
    else
      flash[:error] = "Sorry, something went wrong"
      render 'new'
    end
  end

  def edit
    @supply_options = Supplier.all.map { |d| [ d.company_name,d.id ] }
    @category_options = Category.all.map { |d| [ d.category_name,d.id ] }
    @product = Product.find_by_id(params[:id])
  end

  def update
    @supply_options = Supplier.all.map { |d| [ d.company_name,d.id ] }
    @category_options = Category.all.map { |d| [ d.category_name,d.id ] }
    @product = Product.find_by_id(params[:id])
    if @product.update(product_params)
      flash[:success] = "Product updated successfully."
      redirect_to products_path
    else
      flash[:error] = "Sorry, something went wrong"
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product destroyed successfully"
    redirect_to products_path
  end

  def image_data
    @products = Product.all.paginate(page: params[:page],per_page: 16)
  end

private

  def product_params
    params.require(:product).permit(:product_name,:quantity_per_unit,:unit_price,:unit_in_stock,:recorder_level,:category_id,:supplier_id,:image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_productmodel.html.erb
<!-- Modal -->
      <div class="modal fade" id="exampleModal<%= dep.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">

            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              Are you sure?
            </div>

            <!-- Delete button in the footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
              <%= link_to "Delete", product_path(dep), method: :delete, class: 'btn btn-outline-danger' %>
            </div>

        </div>

app/views/products/_sidebar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to 'Employees',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-th" aria-hidden="true"></i></span>
          <%= link_to "Departments",departments_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user" aria-hidden="true"></i></span>
          <%= link_to "Suppliers",suppliers_path ,class: "nav-link"%>
        </li>

        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tag" aria-hidden="true"></i></span>
          <%= link_to "Categories",categories_path ,class: "nav-link"%>
        </li>
         <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span>
          <%= link_to "Products",products_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-address-card" aria-hidden="true"></i></span>
          <%= link_to "Customers",customers_path ,class: "nav-link"%>
        </li>
        
  </ul>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Add Product</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@product) do |f| %>
            <% if @product.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.file_field :image %>
            <%= f.text_field :product_name,class: 'form-control'%>
            <%= f.select(:category_id, @category_options,{:include_blank => true})%>
            <%= f.select(:supplier_id, @supply_options,{:include_blank => true})%>
            <%= f.text_field :quantity_per_unit %>
            <%= f.text_field :unit_price %>
            <%= f.text_field :unit_in_stock %>
            <%= f.text_field :recorder_level %>

            <%= f.submit "Update Product" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
</div>
<script type="text/javascript">
  $(function() {
    // put your code here
     $('#pre_loader').hide();
});
</script>

app/views/products/image_data.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->

</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>

</div>

<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<div class="container-fluid">
  <%= flash_messages %>
  <div class="row">
   <div class="col-md-12">
    <div class="page-header pt-2">
     <%= link_to 'Add Product', new_product_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
   </div>
  </div>
  </div>
  <section class="wrap page-addVendors">
      <div class="row">
         <% @products.each do |prod|%>
    <div class="col-md-3">
      <div class="block bx-shadow skin-light  stats-card">
        <div class="img-wrap">
          <% if prod.image.present? %>
            <div class="bg-img" style="height: 200px; width: 100%; background-image: url(<%= prod.image_url.to_s%>")>
            </div>
            <% else %>
            <div class="bg-img" style="height: 200px; width: 100%; background-image: url(https://www.pixelstalk.net/wp-content/uploads/2016/07/Green-nature-hd-wallpaper-1080p.jpg")>
            </div>
             <% end %>
            <div class="hoverable">
              <div class="hoverable-content text-center">
             <%= link_to product_path(prod), method: :delete, class: 'icon icon-md del-stats-card' do %>
                <i class="fa fa-times"></i>
                <% end %>
                 <!-- <a data-toggle="modal" data-target="#exampleModal<%= prod.id %>" class="icon icon-md del-stats-card">
                   <i
                   class="fa fa-trash "></i>
                 </a> -->
                
                <!-- <a href="#" class="icon icon-md del-stats-card"><i class="fa fa-times"></i></a> -->
                <a href="#" class="v-btn v-btn-primary btn-sm">View Image</a>
              </div>
            </div>
          </div>
          <div class="content">
            <h4 class="title ft-md"><%= prod.product_name %></h4>
          </div>
        </div>
    </div> 

  <% end %>
  </div>
  </div>
</div>
<%= will_paginate @suppliers, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: "right floated", inner_window: 3 %>
</div>
</section>
</div><!-- /container -->
</div>

<script type="text/javascript">
   var close;
   close = setTimeout(function()
      {
        $('.alert').fadeOut('slow');
        myStop();
  }, 5000);
   function myStop(){
     clearTimeout(close);
   }
   
   $(function() {
    // put your code here
   $('#pre_loader').hide();
});
  </script>

app/views/products/index.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->

</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>

</div>

<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<div class="container-fluid">
  <%= flash_messages %>
  <div class="row">
   <div class="col-md-12">
    <div class="page-header pt-2">
     <%= link_to 'Add Product', new_product_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
   </div>
  </div>
  </div>
  <section class="wrap page-addVendors">
  <!--  TODO Show Product image on click -->
 <div class="row">
   <div class="col-md-12">
   <div class="block bx-shadow skin-light">
     <div class="content">
        <table id="example" class="table table-striped">
         <thead>
          <tr>
            <th>Image</th>
            <th>Product Name</th>
            <th>QuantityPerUnit</th>
            <th>UnitPrice</th>
            <th>UnitInStock</th>
            <th>RecorderLevel</th>
            <th>Action</th>
          </tr>
            </thead>
            <tbody>
             <% @products.each do |prod| %>
             <tr>
               <% if prod.present? %>
               <td><%= image_tag(prod.image_url.to_s , size: "150x100")%></td>
               <td><%= prod.product_name %> </td>
               <td><%= prod.quantity_per_unit %> </td>
               <td><%= prod.unit_price %></td>
               <td><%= prod.unit_in_stock %></td>
               <td><%= prod.recorder_level %></td>
             
               <% end %>
               <td>
                 <%= link_to edit_product_path(prod) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
                 <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                 <% end %>
                 <!-- Delete Button showing the modal Start-->
                 <a data-toggle="modal" data-target="#exampleModal<%= prod.id %>" class="v-btn v-btn-transparent ft-primary icon icon-xs uppercase">
                   <i
                   class="fa fa-trash "></i>
                 </a>
                 <%= render 'productmodel' ,:dep => prod %>
               </td>
             </td>
           </tr>
           <% end %>
         </tbody>
        </table>
      </div>
    </div>
    </div>
  </div>
  </div>
</div>
<%= will_paginate @suppliers, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: "right floated", inner_window: 3 %>
</div>
</section>
</div><!-- /container -->
</div>


<script type="text/javascript">
   var close;
   close = setTimeout(function()
      {
        $('.alert').fadeOut('slow');
        myStop();
  }, 5000);
   function myStop(){
     clearTimeout(close);
   }
   
   $(function() {
    // put your code here
   $('#pre_loader').hide();
});
  </script>

app/views/products/new.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
  <div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<div class="main-container">
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Add Product</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@product) do |f| %>
            <% if @product.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.text_field :product_name,class: 'form-control'%>
            <%= f.file_field :image %>
            <%= f.select(:category_id, @category_options,{:include_blank => true})%>
            <%= f.select(:supplier_id, @supply_options,{:include_blank => true})%>
            <%= f.text_field :quantity_per_unit %>
            <%= f.text_field :unit_price %>
            <%= f.text_field :unit_in_stock %>
            <%= f.text_field :recorder_level %>

            <%= f.submit "Create Product" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
 </div>
<script type="text/javascript">
  $(function() {
    // put your code here
     $('#pre_loader').hide();
});

</script>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>